import { useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { createItem, createTransaction, checkBarcodeBaseExists, getNextItemCode } from '../services/itemService';
import { v4 as uuidv4 } from 'uuid';
import { compressAndUploadImage } from '../services/imageService';
import { useNotification } from '../context/NotificationContext';
import { QRScanner } from '../components/QR/QRScanner';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Modal } from '../components/ui/Modal';
import { VehicleModelSelect } from '../components/VehicleModelSelect';
import { StoreLocationSelect } from '../components/StoreLocationSelect';
import { CategorySelect } from '../components/CategorySelect';
import { VoiceInput } from '../components/VoiceInput';
import { InfoTooltip } from '../components/ui/InfoTooltip';
import { NavIcon } from '../components/icons/NavIcons';

export function AddItem() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user, profile } = useAuth();
  const { success, error: notifyError } = useNotification();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({
    name: '',
    description: '',
    category: '',
    quantity: 1,
    store_location: '',
    vehicle_model: '',
    added_date: new Date().toISOString().slice(0, 10),
    barcode: '',
    photo: null,
  });
  const [showBarcodeScanner, setShowBarcodeScanner] = useState(false);
  const [barcodeAutoGenerated, setBarcodeAutoGenerated] = useState(false);
  const [showCamera, setShowCamera] = useState(false);
  const [cameraError, setCameraError] = useState('');
  const [barcodeError, setBarcodeError] = useState('');
  const [barcodeChecking, setBarcodeChecking] = useState(false);
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  const fileInputRef = useRef(null);
  const barcodeScannerRef = useRef(null);

  const handleChange = (e) => {
    const { name, value, type } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === 'number' ? parseInt(value, 10) || 0 : value,
    }));
    if (name === 'barcode') {
      setBarcodeError('');
      setBarcodeAutoGenerated(false);
    }
  };

  const handleDateChange = (e) => {
    setForm((prev) => ({ ...prev, added_date: e.target.value || new Date().toISOString().slice(0, 10) }));
  };

  const handlePhotoChange = (e) => {
    const file = e.target.files?.[0];
    if (file) setForm((prev) => ({ ...prev, photo: file }));
  };

  const startCamera = async () => {
    setCameraError('');
    try {
      let stream;
      try {
        stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
      } catch {
        stream = await navigator.mediaDevices.getUserMedia({ video: true });
      }
      streamRef.current = stream;
      setShowCamera(true);
    } catch (err) {
      setCameraError(err.message || 'Camera access denied');
      notifyError('Could not open camera');
    }
  };

  useEffect(() => {
    const barcode = searchParams.get('barcode');
    if (barcode) {
      try {
        setForm((prev) => ({ ...prev, barcode: decodeURIComponent(barcode) }));
      } catch {
        setForm((prev) => ({ ...prev, barcode }));
      }
    }
  }, [searchParams]);

  const extractBarcode = (value) => {
    const trimmed = String(value || '').trim();
    try {
      const url = new URL(trimmed);
      const b = url.searchParams.get('barcode');
      return b || trimmed;
    } catch {
      return trimmed;
    }
  };

  // Validate barcode when scanned or entered - check if already registered (by base)
  useEffect(() => {
    const barcode = extractBarcode(form.barcode);
    if (!barcode) {
      setBarcodeError('');
      return;
    }
    const timer = setTimeout(async () => {
      setBarcodeChecking(true);
      setBarcodeError('');
      try {
        const exists = await checkBarcodeBaseExists(barcode);
        setBarcodeError(exists ? 'This barcode/QR code is already registered. Use a different code or find the existing item.' : '');
      } catch {
        setBarcodeError('');
      } finally {
        setBarcodeChecking(false);
      }
    }, 400);
    return () => clearTimeout(timer);
  }, [form.barcode]);

  useEffect(() => {
    if (showCamera && streamRef.current && videoRef.current) {
      const video = videoRef.current;
      video.srcObject = streamRef.current;
      video.play().catch(() => {});
    }
    return () => {
      if (showCamera) {
        streamRef.current?.getTracks().forEach((t) => t.stop());
        streamRef.current = null;
      }
    };
  }, [showCamera]);

  const stopCamera = () => {
    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;
    setShowCamera(false);
    setCameraError('');
  };

  const capturePhoto = () => {
    const video = videoRef.current;
    if (!video || !video.videoWidth) return;
    const canvas = document.createElement('canvas');
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(video, 0, 0);
    canvas.toBlob(
      (blob) => {
        if (blob) {
          const file = new File([blob], `photo-${Date.now()}.jpg`, { type: 'image/jpeg' });
          setForm((prev) => ({ ...prev, photo: file }));
          stopCamera();
        }
      },
      'image/jpeg',
      0.9
    );
  };


  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    if (!form.name.trim()) {
      setError('Item name is required');
      return;
    }
    if (barcodeError) {
      setError('Fix the barcode error before adding.');
      return;
    }
    setLoading(true);
    try {
      const raw = (form.barcode || '').trim();
      let qrId;
      if (raw) {
        const base = extractBarcode(raw);
        const exists = await checkBarcodeBaseExists(base);
        if (exists) {
          setError('This barcode/QR code is already registered. Use a different code or find the existing item.');
          notifyError('Barcode/QR already exists in spare parts');
          setLoading(false);
          return;
        }
        // AGL-INV-* codes are already unique; product barcodes get a suffix
        qrId = base.startsWith('AGL-INV-') ? base : `${base}_${uuidv4().slice(0, 8).toUpperCase()}`;
      } else {
        qrId = await getNextItemCode();
      }

      let photoUrl = null;
      if (form.photo) {
        photoUrl = await compressAndUploadImage(form.photo);
      }

      const item = await createItem({
        qr_id: qrId,
        name: form.name.trim(),
        description: form.description.trim() || null,
        category: form.category.trim() || null,
        quantity: form.quantity || 1,
        store_location: form.store_location.trim() || null,
        vehicle_model: form.vehicle_model.trim() || null,
        model_name: null,
        sku_code: null,
        added_date: form.added_date ? new Date(form.added_date).toISOString() : null,
        photo_url: photoUrl,
        status: 'in_stock',
        added_by: user?.id,
      });
      await createTransaction({
        item_id: item.id,
        type: 'in',
        notes: 'Item registered in spare parts',
        performed_by: user?.id,
      });
      success('Item added. Download QR code PDF from the item page.');
      // Brief delay before navigate to allow DB read-after-write consistency
      await new Promise((r) => setTimeout(r, 300));
      navigate(`/inventory/${item.id}`);
    } catch (err) {
      const msg = err.message || 'Failed to add item';
      setError(msg);
      notifyError(msg);
    } finally {
      setLoading(false);
    }
  };

  const addedByDisplay = profile?.full_name || user?.email || 'Unknown';

  return (
    <div className="w-full max-w-xl min-w-0">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mb-6">
        <h2 className="text-2xl font-bold text-slate-800">Add New Item</h2>
        <p className="text-sm text-slate-500">
          Adding as: <span className="font-medium text-slate-700">{addedByDisplay}</span>
        </p>
      </div>

      <Card className="p-4 sm:p-6 overflow-hidden">
        <form onSubmit={handleSubmit} className="space-y-4 min-w-0">
          {error && (
            <div className="p-3 bg-red-50 text-red-600 rounded-lg text-sm">{error}</div>
          )}

          <div>
            <label className="flex items-center gap-1.5 text-sm font-medium text-slate-700 mb-1">
              Item Name *
              <InfoTooltip text="Use the mic button for voice input to speak the item name." />
            </label>
            <div className="flex gap-2">
              <VoiceInput
                onResult={(text) => setForm((prev) => ({ ...prev, name: (prev.name || '') + (prev.name ? ' ' : '') + text }))}
                className="shrink-0 self-start"
              />
              <Input
                name="name"
                value={form.name}
                onChange={handleChange}
                placeholder="e.g. Car Audio Player"
                className="flex-1 min-w-0"
                required
              />
            </div>
          </div>

          <div>
            <label className="flex items-center gap-1.5 text-sm font-medium text-slate-700 mb-1">
              Product Barcode / QR Code (optional)
              <InfoTooltip text="Scan product barcode/QR — system checks if it exists. If new, a unique suffix is auto-added when saving. Use Auto Generate for internal codes." />
            </label>
            <div className="flex flex-col sm:flex-row gap-2">
              <div className="sm:flex-1 min-w-0">
                <Input
                  name="barcode"
                  value={form.barcode}
                  onChange={handleChange}
                  placeholder="Scan or enter barcode/QR code"
                  error={barcodeError}
                  className={barcodeChecking ? 'opacity-70' : ''}
                />
                {barcodeChecking && (
                  <p className="mt-1 text-xs text-slate-500">Checking if barcode exists...</p>
                )}
                {barcodeAutoGenerated && form.barcode && (
                  <p className="mt-2 px-3 py-2 text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded-lg">
                    If auto-generated, you must print the barcode and place it on the item.
                  </p>
                )}
              </div>
              <Button
                type="button"
                variant="outline"
                onClick={async () => {
                  try {
                    const code = await getNextItemCode();
                    setForm((prev) => ({ ...prev, barcode: code }));
                    setBarcodeError('');
                    setBarcodeAutoGenerated(true);
                  } catch (err) {
                    notifyError(err.message || 'Failed to generate code');
                  }
                }}
                className="shrink-0 p-2"
                title="Auto Generate"
              >
                <NavIcon name="sparkles" className="w-5 h-5" />
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => setShowBarcodeScanner(true)}
                className="shrink-0"
              >
                Scan
              </Button>
            </div>
          </div>

          {showBarcodeScanner && (
            <Modal onBackdropClick={async () => {
              try { await barcodeScannerRef.current?.stop?.(); } catch { /* ignore */ }
              setShowBarcodeScanner(false);
            }}>
              <Card className="p-6 relative">
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <h3 className="font-semibold text-slate-800">Scan Barcode / QR Code</h3>
                    <p className="text-sm text-slate-500 mt-1">Point your camera at the barcode or QR code.</p>
                  </div>
                  <button
                    type="button"
                    onClick={async () => {
                      try { await barcodeScannerRef.current?.stop?.(); } catch { /* ignore */ }
                      setShowBarcodeScanner(false);
                    }}
                    className="p-2 -m-2 rounded-lg hover:bg-slate-100 text-slate-500 hover:text-slate-700"
                    aria-label="Close"
                  >
                    <NavIcon name="close" className="w-5 h-5" />
                  </button>
                </div>
                <QRScanner
                  ref={barcodeScannerRef}
                  scannerId="add-item-barcode-scanner"
                  autoStart
                  onScan={async (code) => {
                    const base = extractBarcode(code);
                    if (!base) return;
                    try {
                      const exists = await checkBarcodeBaseExists(base);
                      if (exists) {
                        setBarcodeError('This barcode/QR code is already registered.');
                        notifyError('Barcode already in use — scan a different code');
                        return;
                      }
                      setForm((prev) => ({ ...prev, barcode: base }));
                      setBarcodeError('');
                      setBarcodeAutoGenerated(false);
                      try { await barcodeScannerRef.current?.stop?.(); } catch { /* ignore */ }
                      setShowBarcodeScanner(false);
                      success('Barcode captured. A unique suffix will be added when you save.');
                    } catch (err) {
                      notifyError(err.message || 'Failed to check barcode');
                    }
                  }}
                  onError={(msg) => notifyError(msg)}
                />
              </Card>
            </Modal>
          )}

          <div className="min-w-0">
            <label className="flex items-center gap-1.5 text-sm font-medium text-slate-700 mb-1">
              Description
              <InfoTooltip text="Optional details about the spare part. Use the mic for voice input." />
            </label>
            <div className="flex gap-2">
              <VoiceInput
                onResult={(text) => setForm((prev) => ({ ...prev, description: (prev.description || '') + (prev.description ? ' ' : '') + text }))}
                className="shrink-0 self-start"
              />
              <textarea
                name="description"
                value={form.description}
                onChange={handleChange}
                placeholder="Optional details..."
                rows={3}
                className="flex-1 min-w-0 px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-asahi/30 focus:border-asahi outline-none"
              />
            </div>
          </div>

          <CategorySelect
            label="Category"
            name="category"
            value={form.category}
            onChange={handleChange}
            placeholder="Select category"
          />

          <StoreLocationSelect
            label="Store Location"
            name="store_location"
            value={form.store_location}
            onChange={handleChange}
            placeholder="Select location"
          />

          <VehicleModelSelect
            label="Vehicle Model (optional)"
            name="vehicle_model"
            value={form.vehicle_model}
            onChange={handleChange}
            placeholder="Select vehicle make"
          />

          <Input
            label="Added Date"
            name="added_date"
            type="date"
            value={form.added_date}
            onChange={handleDateChange}
          />

          <Input
            label="Quantity"
            name="quantity"
            type="number"
            min={1}
            value={form.quantity}
            onChange={handleChange}
          />

          <div className="min-w-0">
            <label className="flex items-center gap-1.5 text-sm font-medium text-slate-700 mb-2">
              Product Image
              <InfoTooltip text="Capture a photo with camera or choose from your device. Helps identify the spare part." />
            </label>
            <div className="flex flex-wrap gap-2">
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handlePhotoChange}
                className="hidden"
              />
              <Button
                type="button"
                onClick={startCamera}
                className="ring-2 ring-asahi ring-offset-2 p-3"
                title="Open Camera"
              >
                <NavIcon name="camera" className="w-6 h-6" />
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => fileInputRef.current?.click()}
                className="p-3"
                title="Choose from Library"
              >
                <NavIcon name="folder" className="w-6 h-6" />
              </Button>
            </div>
            {form.photo && (
              <div className="mt-3 flex items-center gap-3 min-w-0">
                <img
                  src={URL.createObjectURL(form.photo)}
                  alt="Preview"
                  className="w-20 h-20 shrink-0 rounded-lg object-cover border border-slate-200"
                />
                <p className="text-sm text-slate-500 truncate">Chosen: {form.photo.name}</p>
              </div>
            )}
          </div>

          {showCamera &&
            createPortal(
              <>
                <div className="fixed inset-0 z-[100] bg-black/80" onClick={stopCamera} />
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 pt-24 pb-20 overflow-y-auto">
                  <div className="bg-slate-900 rounded-xl overflow-hidden max-w-lg w-full" onClick={(e) => e.stopPropagation()}>
                    <video
                      ref={videoRef}
                      autoPlay
                      playsInline
                      muted
                      className="w-full aspect-video object-cover"
                    />
                    {cameraError && (
                      <p className="p-4 text-amber-400 text-sm">{cameraError}</p>
                    )}
                    <div className="flex gap-2 p-4 bg-slate-800">
                      <Button onClick={capturePhoto} className="flex-1">
                        Capture
                      </Button>
                      <Button variant="secondary" onClick={stopCamera}>
                        Cancel
                      </Button>
                    </div>
                  </div>
                </div>
              </>,
              document.body
            )}

          <div className="flex flex-col-reverse sm:flex-row gap-3 pt-4">
            <Button type="submit" disabled={loading} className="w-full sm:w-auto">
              {loading ? 'Adding...' : 'Add Spare Part'}
            </Button>
            <Button type="button" variant="secondary" onClick={() => navigate(-1)} className="w-full sm:w-auto">
              Cancel
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
