import { useState, useRef, useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { createItem, createTransaction, createItemBarcodes, checkBarcodeBaseExists, getNextItemCode, searchItemNames } from '../services/itemService';
import { v4 as uuidv4 } from 'uuid';
import { compressAndUploadImage } from '../services/imageService';
import { useNotification } from '../context/NotificationContext';
import { QRScanner } from '../components/QR/QRScanner';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { ProductImage, ImageUploadOverlay } from '../components/ui/ProductImage';
import { Modal } from '../components/ui/Modal';
import { VehicleFitmentEditor } from '../components/VehicleFitmentEditor';
import { hasRequiredVehicleFitments, finalizeVehicleFitments, isVehicleMakeRequired } from '../lib/vehicleFitments';
import { useCategories } from '../hooks/useCategories';
import { StoreLocationSelect } from '../components/StoreLocationSelect';
import { CategorySelect } from '../components/CategorySelect';
import { NavIcon } from '../components/icons/NavIcons';
import { PageContainer, PageHeader } from '../components/ui/PageLayout';
import { FormField } from '../components/ui/FormField';
import { formInputClass, formTextareaClass } from '../lib/formFieldStyles';
import {
  extractBarcode,
  sanitizeBarcodeInput,
  wasBarcodeCorrected,
  barcodeLengthError,
  BARCODE_MAX_LENGTH,
} from '../lib/barcodeUtils';

export function AddItem() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user, profile } = useAuth();
  const { success, error: notifyError } = useNotification();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({
    name: '',
    description: '',
    category: '',
    quantity: 1,
    store_location: '',
    vehicle_fitments: [],
    agl_number: 'AGL000',
    unit_price: '',
    added_date: new Date().toISOString().slice(0, 10),
    barcodes: [''],
    photo: null,
  });
  const [showBarcodeScanner, setShowBarcodeScanner] = useState(false);
  const [barcodeAutoGenerated, setBarcodeAutoGenerated] = useState(false);
  const [showCamera, setShowCamera] = useState(false);
  const [cameraError, setCameraError] = useState('');
  const [barcodeError, setBarcodeError] = useState('');
  const [barcodeHint, setBarcodeHint] = useState('');
  const [barcodeChecking, setBarcodeChecking] = useState(false);
  const [nameSuggestions, setNameSuggestions] = useState([]);
  const [nameSuggestionsOpen, setNameSuggestionsOpen] = useState(false);
  const [nameSuggestionsLoading, setNameSuggestionsLoading] = useState(false);
  const nameSuggestionsTimerRef = useRef(null);
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  const fileInputRef = useRef(null);
  const barcodeScannerRef = useRef(null);
  const barcodeInputRefs = useRef([]);
  const lastFocusedBarcodeIndex = useRef(0);
  const barcodeSanitizeTimers = useRef({});

  const photoPreviewUrl = useMemo(
    () => (form.photo ? URL.createObjectURL(form.photo) : null),
    [form.photo]
  );

  useEffect(() => {
    return () => {
      if (photoPreviewUrl) URL.revokeObjectURL(photoPreviewUrl);
    };
  }, [photoPreviewUrl]);

  const handleChange = (e) => {
    const { name, value, type } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]:
        type === 'number'
          ? name === 'unit_price'
            ? value
            : parseInt(value, 10) || 0
          : value,
    }));
    if (name.startsWith('barcode_')) {
      setBarcodeError('');
      setBarcodeAutoGenerated(false);
    }
  };

  const commitBarcodeValue = (index, rawValue) => {
    const raw = String(rawValue ?? '').trim();
    const clean = sanitizeBarcodeInput(raw);
    const lengthErr = barcodeLengthError(clean);

    setForm((prev) => {
      const next = [...(prev.barcodes || [''])];
      next[index] = clean;
      return { ...prev, barcodes: next };
    });
    setBarcodeAutoGenerated(false);

    if (lengthErr) {
      setBarcodeError(lengthErr);
      setBarcodeHint('');
      return;
    }

    setBarcodeError('');
    if (wasBarcodeCorrected(raw)) {
      setBarcodeHint('Repeated scan removed — kept one barcode only.');
    } else {
      setBarcodeHint('');
    }
  };

  const handleBarcodeChange = (index, value) => {
    setForm((prev) => {
      const next = [...(prev.barcodes || [''])];
      next[index] = value;
      return { ...prev, barcodes: next };
    });
    setBarcodeError('');
    setBarcodeHint('');
    setBarcodeAutoGenerated(false);

    clearTimeout(barcodeSanitizeTimers.current[index]);
    barcodeSanitizeTimers.current[index] = setTimeout(() => {
      setForm((prev) => {
        const raw = (prev.barcodes || [''])[index];
        if (!raw || !wasBarcodeCorrected(raw)) return prev;
        const next = [...(prev.barcodes || [''])];
        next[index] = sanitizeBarcodeInput(raw);
        setBarcodeHint('Repeated scan removed — kept one barcode only.');
        return { ...prev, barcodes: next };
      });
    }, 400);
  };

  const addBarcodeInput = () => {
    setForm((prev) => {
      const barcodes = prev.barcodes || [''];
      const next = [...barcodes, ''];
      setTimeout(() => barcodeInputRefs.current[next.length - 1]?.focus(), 50);
      return { ...prev, barcodes: next };
    });
  };

  const removeBarcodeInput = (index) => {
    setForm((prev) => {
      const barcodes = prev.barcodes || [''];
      const next = barcodes.filter((_, i) => i !== index);
      return { ...prev, barcodes: next.length ? next : [''] };
    });
  };

  const handleDateChange = (e) => {
    setForm((prev) => ({ ...prev, added_date: e.target.value || new Date().toISOString().slice(0, 10) }));
  };

  const handlePhotoChange = (e) => {
    const file = e.target.files?.[0];
    if (file) setForm((prev) => ({ ...prev, photo: file }));
  };

  const startCamera = async () => {
    setCameraError('');
    try {
      let stream;
      try {
        stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
      } catch {
        stream = await navigator.mediaDevices.getUserMedia({ video: true });
      }
      streamRef.current = stream;
      setShowCamera(true);
    } catch (err) {
      setCameraError(err.message || 'Camera access denied');
      notifyError('Could not open camera');
    }
  };

  useEffect(() => {
    barcodeInputRefs.current[0]?.focus();
  }, []);

  useEffect(() => {
    const barcode = searchParams.get('barcode');
    if (barcode) {
      try {
        const decoded = decodeURIComponent(barcode);
        setForm((prev) => ({ ...prev, barcodes: [sanitizeBarcodeInput(decoded)] }));
      } catch {
        setForm((prev) => ({ ...prev, barcodes: [sanitizeBarcodeInput(barcode)] }));
      }
    }
  }, [searchParams]);

  // Validate barcodes when scanned or entered - check if already registered
  const allBarcodes = form.barcodes.map((b) => sanitizeBarcodeInput(b)).filter(Boolean);
  useEffect(() => {
    if (allBarcodes.length === 0) {
      setBarcodeError('');
      return;
    }
    const timer = setTimeout(async () => {
      setBarcodeChecking(true);
      setBarcodeError('');
      try {
        for (const barcode of allBarcodes) {
          const exists = await checkBarcodeBaseExists(barcode);
          if (exists) {
            setBarcodeError('Already filled — this barcode is registered. Scan a different code or find the existing item.');
            notifyError('Already filled — this barcode is registered.');
            break;
          }
        }
      } catch {
        setBarcodeError('');
      } finally {
        setBarcodeChecking(false);
      }
    }, 400);
    return () => clearTimeout(timer);
  }, [form.barcodes.join('|')]);

  useEffect(() => {
    const q = form.name.trim();
    if (q.length < 2) {
      setNameSuggestions([]);
      setNameSuggestionsOpen(false);
      return;
    }
    if (nameSuggestionsTimerRef.current) clearTimeout(nameSuggestionsTimerRef.current);
    nameSuggestionsTimerRef.current = setTimeout(async () => {
      setNameSuggestionsLoading(true);
      try {
        const list = await searchItemNames(q);
        setNameSuggestions(list);
        setNameSuggestionsOpen(list.length > 0);
      } catch {
        setNameSuggestions([]);
        setNameSuggestionsOpen(false);
      } finally {
        setNameSuggestionsLoading(false);
      }
    }, 250);
    return () => {
      if (nameSuggestionsTimerRef.current) clearTimeout(nameSuggestionsTimerRef.current);
    };
  }, [form.name]);

  useEffect(() => {
    if (showCamera && streamRef.current && videoRef.current) {
      const video = videoRef.current;
      video.srcObject = streamRef.current;
      video.play().catch(() => {});
    }
    return () => {
      if (showCamera) {
        streamRef.current?.getTracks().forEach((t) => t.stop());
        streamRef.current = null;
      }
    };
  }, [showCamera]);

  const stopCamera = () => {
    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;
    setShowCamera(false);
    setCameraError('');
  };

  const capturePhoto = () => {
    const video = videoRef.current;
    if (!video || !video.videoWidth) return;
    const canvas = document.createElement('canvas');
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(video, 0, 0);
    canvas.toBlob(
      (blob) => {
        if (blob) {
          const file = new File([blob], `photo-${Date.now()}.jpg`, { type: 'image/jpeg' });
          setForm((prev) => ({ ...prev, photo: file }));
          stopCamera();
        }
      },
      'image/jpeg',
      0.9
    );
  };


  const { categories } = useCategories();

  const vehicleMakeRequired = useMemo(
    () => isVehicleMakeRequired(form.category, categories),
    [form.category, categories]
  );

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    if (!form.name.trim()) {
      setError('Item name is required');
      return;
    }
    if (!form.category?.trim()) {
      setError('Category is required');
      return;
    }
    if (!form.agl_number?.trim()) {
      setError('AGL number is required');
      return;
    }
    if (!hasRequiredVehicleFitments(form.vehicle_fitments, form.category, categories)) {
      setError('Select at least one vehicle make');
      return;
    }
    let unitPrice = null;
    if (form.unit_price !== '' && form.unit_price != null) {
      const parsed = Number(form.unit_price);
      if (!Number.isFinite(parsed) || parsed < 0) {
        setError('Unit price must be a valid number');
        return;
      }
      unitPrice = parsed;
    }
    const allBarcodesTrimmed = (form.barcodes || []).map((b) => String(b || '').trim()).filter(Boolean);
    if (allBarcodesTrimmed.length === 0) {
      setError('At least one product barcode/QR code is required. Scan, enter, or use Auto Generate.');
      return;
    }
    if (barcodeError) {
      setError('Fix the barcode error before adding.');
      return;
    }
    setLoading(true);
    try {
      // Validate all barcodes are unique and not already registered
      const bases = allBarcodesTrimmed.map((b) => sanitizeBarcodeInput(b));
      const uniqueBases = [...new Set(bases)];
      if (uniqueBases.length !== bases.length) {
        setError('Duplicate barcodes detected. Each barcode must be unique.');
        setLoading(false);
        return;
      }
      for (const base of bases) {
        const exists = await checkBarcodeBaseExists(base);
        if (exists) {
          setError(`Barcode "${base}" is already registered. Use a different code or find the existing item.`);
          notifyError('Barcode/QR already exists in spare parts');
          setLoading(false);
          return;
        }
      }

      const primaryRaw = allBarcodesTrimmed[0];
      const primaryBase = extractBarcode(primaryRaw);
      const qrId = primaryBase.startsWith('AGL-INV-')
        ? primaryBase
        : `${primaryBase}_${uuidv4().slice(0, 8).toUpperCase()}`;

      let photoUrl = null;
      if (form.photo) {
        photoUrl = await compressAndUploadImage(form.photo);
      }

      const vehicle_fitments = finalizeVehicleFitments(form.vehicle_fitments);

      const item = await createItem({
        qr_id: qrId,
        name: form.name.trim(),
        description: form.description.trim() || null,
        category: form.category.trim(),
        quantity: form.quantity || 1,
        store_location: form.store_location.trim() || null,
        vehicle_fitments,
        agl_number: form.agl_number.trim(),
        unit_price: unitPrice,
        added_date: form.added_date
          ? (new Date().toISOString().slice(0, 10) === form.added_date
              ? new Date()
              : new Date(form.added_date + 'T12:00:00')
            ).toISOString()
          : null,
        photo_url: photoUrl,
        status: 'in_stock',
        added_by: user?.id,
      });
      await createTransaction({
        item_id: item.id,
        type: 'created',
        notes: 'Item registered in spare parts',
        performed_by: user?.id,
      });
      if (bases.length > 1) {
        await createItemBarcodes(item.id, bases.slice(1));
      }
      success('Item added. Download QR code PDF from the item page.');
      // Brief delay before navigate to allow DB read-after-write consistency
      await new Promise((r) => setTimeout(r, 300));
      navigate(`/inventory/${item.id}`);
    } catch (err) {
      const msg = err.message || 'Failed to add item';
      setError(msg);
      notifyError(msg);
    } finally {
      setLoading(false);
    }
  };

  const addedByDisplay = profile?.full_name || user?.email || 'Unknown';

  return (
    <PageContainer width="narrow">
      <PageHeader
        title="Add spare part"
        subtitle={`Adding as ${addedByDisplay}`}
      />

      <Card className="p-4 sm:p-6 overflow-hidden">
        <form onSubmit={handleSubmit} className="space-y-4 min-w-0">
          {error && (
            <div className="p-3 bg-red-50 text-red-600 rounded-lg text-sm">{error}</div>
          )}

          <FormField variant="name" label="Item Name" required>
            <div className="relative">
            <Input
              name="name"
              variant="name"
              value={form.name}
              onChange={handleChange}
              onFocus={() => form.name.trim().length >= 2 && nameSuggestions.length > 0 && setNameSuggestionsOpen(true)}
              onBlur={() => setTimeout(() => setNameSuggestionsOpen(false), 150)}
              placeholder="e.g. Car Audio Player"
              required
            />
            {(nameSuggestionsOpen || nameSuggestionsLoading) && form.name.trim().length >= 2 && (
              <div className="absolute z-10 mt-1 w-full bg-white border border-slate-200 rounded-lg shadow-lg py-1 max-h-48 overflow-y-auto">
                {nameSuggestionsLoading ? (
                  <div className="px-4 py-3 text-sm text-slate-500">Searching...</div>
                ) : nameSuggestions.length > 0 ? (
                  <ul>
                    {nameSuggestions.map((s) => (
                      <li key={s}>
                        <button
                          type="button"
                          onMouseDown={(e) => {
                            e.preventDefault();
                            setForm((prev) => ({ ...prev, name: s }));
                            setNameSuggestionsOpen(false);
                          }}
                          className="w-full px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50"
                        >
                          {s}
                        </button>
                      </li>
                    ))}
                  </ul>
                ) : null}
              </div>
            )}
            </div>
          </FormField>

          <FormField
            variant="barcode"
            label="Product Barcode / QR Code"
            required
            hint="Physical scanner: focus here and scan. Camera: click Scan. Or type manually."
          >
            <div className="flex flex-col gap-2">
              {(form.barcodes || ['']).map((barcode, index) => (
                <div key={index} className="flex gap-2 items-center">
                  {index > 0 && (
                    <button
                      type="button"
                      onClick={() => removeBarcodeInput(index)}
                      className="shrink-0 p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 hover:text-slate-700"
                      title="Remove this barcode"
                      aria-label="Remove barcode"
                    >
                      <NavIcon name="close" className="w-4 h-4" />
                    </button>
                  )}
                  <input
                    ref={(el) => { barcodeInputRefs.current[index] = el; }}
                    data-barcode-input="true"
                    onFocus={() => { lastFocusedBarcodeIndex.current = index; }}
                    value={barcode}
                    onChange={(e) => handleBarcodeChange(index, e.target.value)}
                    onBlur={(e) => commitBarcodeValue(index, e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        commitBarcodeValue(index, e.target.value ?? barcode);
                      }
                    }}
                    maxLength={BARCODE_MAX_LENGTH * 2}
                    placeholder={index === 0 ? 'Focus here, then scan — or click Scan for camera' : `Barcode ${index + 1}`}
                    className={`flex-1 min-w-0 ${formInputClass('barcode', barcodeError ? 'border-red-500 focus:border-red-500 focus:ring-red-200' : '')} ${barcodeChecking ? 'opacity-70' : ''}`}
                  />
                  {index === 0 && (
                    <button
                      type="button"
                      onClick={addBarcodeInput}
                      className="shrink-0 p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
                      title="Add another barcode"
                      aria-label="Add barcode"
                    >
                      <NavIcon name="add" className="w-4 h-4" />
                    </button>
                  )}
                </div>
              ))}
              <div className="flex gap-2 shrink-0">
                {(form.barcodes || ['']).some((b) => b?.trim()) ? (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => {
                      const idx = lastFocusedBarcodeIndex.current;
                      if (idx >= 0 && idx < (form.barcodes || []).length) {
                        handleBarcodeChange(idx, '');
                        setBarcodeError('');
                        setBarcodeAutoGenerated(false);
                      }
                    }}
                    className="p-2"
                    title="Clear focused barcode"
                    aria-label="Clear focused barcode"
                  >
                    <NavIcon name="close" className="w-5 h-5" />
                  </Button>
                ) : (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={async () => {
                      try {
                        const code = await getNextItemCode();
                        handleBarcodeChange(0, code);
                        setBarcodeError('');
                        setBarcodeAutoGenerated(true);
                      } catch (err) {
                        notifyError(err.message || 'Failed to generate code');
                      }
                    }}
                    className="p-2"
                    title="Auto Generate"
                  >
                    <NavIcon name="sparkles" className="w-5 h-5" />
                  </Button>
                )}
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setShowBarcodeScanner(true)}
                >
                  Scan
                </Button>
              </div>
            </div>
            {barcodeHint && !barcodeError && (
              <p className="mt-1 text-xs text-amber-700 bg-amber-50 border border-amber-100 rounded-lg px-3 py-2">
                {barcodeHint}
              </p>
            )}
            {barcodeError && (
              <div className="mt-2 px-3 py-2.5 flex items-start gap-2 text-sm text-red-800 bg-red-50 border border-red-200 rounded-lg">
                <NavIcon name="warning" className="w-5 h-5 shrink-0 mt-0.5 text-red-600" />
                <span>{barcodeError}</span>
              </div>
            )}
            {barcodeChecking && (
              <p className="mt-1 text-xs text-slate-500">Checking if barcode exists...</p>
            )}
            {barcodeAutoGenerated && (form.barcodes || [''])[0]?.trim() && (
              <p className="mt-2 px-3 py-2 text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded-lg">
                If auto-generated, you must print the barcode and place it on the item.
              </p>
            )}
          </FormField>

          {showBarcodeScanner && (
            <Modal onBackdropClick={async () => {
              try { await barcodeScannerRef.current?.stop?.(); } catch { /* ignore */ }
              setShowBarcodeScanner(false);
            }}>
              <Card className="p-6 relative">
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <h3 className="font-semibold text-slate-800">Scan Barcode / QR Code</h3>
                    <p className="text-sm text-slate-500 mt-1">Point camera at the code. Hold steady, ensure good lighting.</p>
                  </div>
                  <button
                    type="button"
                    onClick={async () => {
                      try { await barcodeScannerRef.current?.stop?.(); } catch { /* ignore */ }
                      setShowBarcodeScanner(false);
                    }}
                    className="p-2 -m-2 rounded-lg hover:bg-slate-100 text-slate-500 hover:text-slate-700"
                    aria-label="Close"
                  >
                    <NavIcon name="close" className="w-5 h-5" />
                  </button>
                </div>
                <QRScanner
                  ref={barcodeScannerRef}
                  scannerId="add-item-barcode-scanner"
                  autoStart
                  onScan={async (code) => {
                    const base = sanitizeBarcodeInput(extractBarcode(code));
                    if (!base) return;
                    try {
                      const exists = await checkBarcodeBaseExists(base);
                      if (exists) {
                        setBarcodeError('This barcode/QR code is already registered.');
                        notifyError('Barcode already in use — scan a different code');
                        return;
                      }
                      setForm((prev) => {
                        const barcodes = [...(prev.barcodes || [''])];
                        const idx = barcodes.findIndex((b) => !String(b || '').trim());
                        if (idx >= 0) {
                          barcodes[idx] = base;
                          return { ...prev, barcodes };
                        }
                        return { ...prev, barcodes: [...barcodes, base] };
                      });
                      setBarcodeError('');
                      setBarcodeAutoGenerated(false);
                      try { await barcodeScannerRef.current?.stop?.(); } catch { /* ignore */ }
                      setShowBarcodeScanner(false);
                      success('Barcode captured. A unique suffix will be added when you save.');
                    } catch (err) {
                      notifyError(err.message || 'Failed to check barcode');
                    }
                  }}
                  onError={(msg) => notifyError(msg)}
                />
              </Card>
            </Modal>
          )}

          <FormField variant="agl" label="AGL number" required>
          <Input
            name="agl_number"
            variant="agl"
            value={form.agl_number}
            onChange={handleChange}
            placeholder="AGL000"
            required
          />
          </FormField>

          <FormField variant="price" label="Unit price £ (optional)">
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500 pointer-events-none">£</span>
              <input
                name="unit_price"
                type="number"
                min={0}
                step="0.01"
                value={form.unit_price}
                onChange={handleChange}
                placeholder="12.50"
                className={`pl-8 pr-4 ${formInputClass('price')}`}
              />
            </div>
          </FormField>

          <FormField variant="description" label="Description" hint="Optional details about the spare part.">
            <textarea
                name="description"
                value={form.description}
                onChange={handleChange}
                placeholder="Optional details..."
                rows={3}
                className={formTextareaClass('description', 'min-w-0')}
              />
          </FormField>

          <FormField variant="category" label="Category" required>
          <CategorySelect
            name="category"
            value={form.category}
            onChange={handleChange}
            placeholder="Select category"
            required
            showLabel={false}
          />
          </FormField>

          <FormField variant="location" label="Store Location">
          <StoreLocationSelect
            name="store_location"
            value={form.store_location}
            onChange={handleChange}
            placeholder="Select location"
            showLabel={false}
          />
          </FormField>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <FormField variant="quantity" label="Quantity" hint="Total stock — low-stock alert when below 2 units.">
          <Input
            name="quantity"
            type="number"
            min={1}
            variant="quantity"
            value={form.quantity}
            onChange={handleChange}
          />
          </FormField>
          </div>

          <FormField
            variant="vehicle"
            label="Vehicle compatibility"
            required={vehicleMakeRequired}
            hint={vehicleMakeRequired ? undefined : 'Vehicle make/model is optional for this category.'}
          >
          <VehicleFitmentEditor
            value={form.vehicle_fitments}
            onChange={(fitments) => setForm((prev) => ({ ...prev, vehicle_fitments: fitments }))}
            required={vehicleMakeRequired}
          />
          </FormField>

          <FormField variant="date" label="Added Date">
          <Input
            name="added_date"
            type="date"
            variant="date"
            value={form.added_date}
            onChange={handleDateChange}
          />
          </FormField>

          <FormField variant="photo" label="Product Image" hint="Capture a photo with camera or choose from your device. Helps identify the spare part.">
            <div className="flex flex-wrap gap-2">
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handlePhotoChange}
                className="hidden"
              />
              <Button
                type="button"
                onClick={startCamera}
                className="ring-2 ring-orange-400 ring-offset-2 p-3"
                title="Open Camera"
              >
                <NavIcon name="camera" className="w-6 h-6" />
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => fileInputRef.current?.click()}
                className="p-3 border-orange-300 text-orange-800 hover:bg-orange-50"
                title="Choose from Library"
              >
                <NavIcon name="folder" className="w-6 h-6" />
              </Button>
            </div>
            {form.photo && (
              <div className="mt-3 flex items-center gap-3 min-w-0">
                <div className="relative shrink-0">
                  <ProductImage
                    src={photoPreviewUrl}
                    alt="Preview"
                    className="w-20 h-20 rounded-lg border-2 border-orange-200"
                    iconClassName="w-8 h-8"
                  />
                  <ImageUploadOverlay show={loading} />
                </div>
                <p className="text-sm text-slate-500 truncate">Chosen: {form.photo.name}</p>
              </div>
            )}
          </FormField>

          {showCamera &&
            createPortal(
              <>
                <div className="fixed inset-0 z-[100] bg-black/80" onClick={stopCamera} />
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 pt-24 pb-20 overflow-y-auto">
                  <div className="bg-slate-900 rounded-xl overflow-hidden max-w-lg w-full" onClick={(e) => e.stopPropagation()}>
                    <video
                      ref={videoRef}
                      autoPlay
                      playsInline
                      muted
                      className="w-full aspect-video object-cover"
                    />
                    {cameraError && (
                      <p className="p-4 text-amber-400 text-sm">{cameraError}</p>
                    )}
                    <div className="flex gap-2 p-4 bg-slate-800">
                      <Button onClick={capturePhoto} className="flex-1">
                        Capture
                      </Button>
                      <Button variant="secondary" onClick={stopCamera}>
                        Cancel
                      </Button>
                    </div>
                  </div>
                </div>
              </>,
              document.body
            )}

          <div className="flex flex-col-reverse sm:flex-row gap-3 pt-4">
            <Button type="submit" loading={loading} disabled={loading} className="w-full sm:w-auto">
              {loading ? 'Adding…' : 'Add Spare Part'}
            </Button>
            <Button type="button" variant="secondary" onClick={() => navigate(-1)} className="w-full sm:w-auto">
              Cancel
            </Button>
          </div>
        </form>
      </Card>
    </PageContainer>
  );
}
