export default {
	name: "inventoryItem",
	title: "Inventory Item",
	type: "document",
	fields: [
		{ name: "qrId", title: "QR / Barcode ID", type: "string", validation: (R) => R.required() },
		{ name: "name", title: "Name", type: "string", validation: (R) => R.required() },
		{ name: "description", title: "Description", type: "text" },
		{ name: "category", title: "Category", type: "string" },
		{ name: "photo", title: "Photo", type: "image" },
		{ name: "photoUrl", title: "Photo URL (legacy)", type: "url" },
		{ name: "quantity", title: "Quantity", type: "number", initialValue: 1 },
		{
			name: "status",
			title: "Status",
			type: "string",
			options: { list: ["in_stock", "out", "reserved"] },
			initialValue: "in_stock",
		},
		{ name: "addedDate", title: "Added Date", type: "datetime" },
		{ name: "lastUsedDate", title: "Last Used Date", type: "datetime" },
		{ name: "vehicleModel", title: "Vehicle Model (legacy)", type: "string" },
		{
			name: "vehicleModels",
			title: "Vehicle Models",
			type: "array",
			of: [{ type: "string" }],
		},
		{ name: "storeLocation", title: "Store Location", type: "string" },
		{ name: "modelName", title: "Model Name", type: "string" },
		{ name: "skuCode", title: "SKU Code", type: "string" },
		{ name: "aglNumber", title: "AGL Number", type: "string" },
		{ name: "unitPrice", title: "Unit Price", type: "number" },
		{ name: "reminderCount", title: "Low Stock Alert At", type: "number", initialValue: 1 },
		{ name: "addedBy", title: "Added By", type: "reference", to: [{ type: "appUser" }] },
		{ name: "lastUsedBy", title: "Last Used By", type: "reference", to: [{ type: "appUser" }] },
	],
};
